### ISSUE TITLE
Chromedirver file permission error

### ISSUE THREAD

**Issue by jagalile** [jagalile/ivoox-scraping#4]
`Traceback (most recent call last):
  File "/home/javier/scripts/ivoox-scraping/src/web_scraper.py", line 37, in _chromedriver_driver
    return webdriver.Chrome(self._driver_path(), chrome_options=self.options)
  File "/home/javier/scripts/ivoox-scraping/src/web_scraper.py", line 48, in _driver_path
    raise Exception('Chromedriver missing!')
Exception: Chromedriver missing!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/javier/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/javier/scripts/ivoox-scraping/chromedriver/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/javier/scripts/ivoox-scraping/main.py", line 32, in <module>
    main(args['podcast_name'][0], args['chapter_name'][0])
  File "/home/javier/scripts/ivoox-scraping/main.py", line 28, in main
    dp = DownloadPodcast(podcast_name, chapter_search_name=chapter)
  File "/home/javier/scripts/ivoox-scraping/src/download_podcast.py", line 16, in __init__
    self.web_scraping = WebScraper()
  File "/home/javier/scripts/ivoox-scraping/src/web_scraper.py", line 21, in __init__
    self.driver = self._chromedriver_driver
  File "/home/javier/scripts/ivoox-scraping/src/web_scraper.py", line 40, in _chromedriver_driver
    return webdriver.Chrome(self._driver_path(), chrome_options=self.options)
  File "/home/javier/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/javier/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/javier/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home`

**Comment by jagalile** [comment]
Fixed in this release #6
